# Generated by Django 4.2.17 on 2025-01-05 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_plus_django_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
