# Generated by Django 4.2.17 on 2024-12-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_plus_django_app', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tg_username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
