# Generated by Django 4.2.17 on 2025-01-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_plus_django_app', '0004_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.TextField()),
                ('model_name_for_customer', models.TextField()),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('category', models.CharField()),
                ('images_paths', models.JSONField()),
            ],
        ),
    ]
