# Generated by Django 4.2.17 on 2024-12-15 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_plus_django_app', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
