# Generated by Django 4.2.17 on 2025-01-09 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_plus_django_app', '0009_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
