# Generated by Django 4.2.17 on 2025-01-11 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_plus_django_app', '0011_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
