# Generated by Django 4.2.17 on 2025-02-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tg_plus_django_app', '0018_delete_product_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(help_text='["ps5", "Playstation 5"]')),
                ('description', models.TextField(help_text='Description')),
                ('price', models.FloatField()),
                ('category', models.JSONField(help_text='["game_consoles", "Игровые консоли"]')),
                ('brand', models.JSONField(help_text='["sony", "Sony"]')),
                ('ratings', models.JSONField(blank=True, null=True)),
                ('images_paths', models.JSONField(help_text='{"1": "/static/category_pics/game_consoles/ps5.png"}')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField()),
                ('tg_username', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('orders', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
