# Generated by Django 4.2.17 on 2024-12-20 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_plus_django_app', '0020_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
