# Generated by Django 4.2.17 on 2024-12-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_plus_django_app', '0022_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.CharField(default='2024-12-20 | 20:23:01 | RTZ 2 (зима)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.CharField(default='2024-12-20 | 20:23:01 | RTZ 2 (зима)'),
        ),
    ]
