# Generated by Django 4.2.17 on 2024-12-21 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_plus_django_app', '0024_product_alter_user_created_at_alter_user_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
