# Generated by Django 4.2.17 on 2024-12-21 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_plus_django_app', '0026_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
