# Generated by Django 4.2.17 on 2024-12-21 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_plus_django_app', '0028_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.CharField(default='2024-12-21 | 07:05:03 +0300 | RTZ 2 (зима)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.CharField(default='2024-12-21 | 07:05:03 +0300 | RTZ 2 (зима)'),
        ),
    ]
