# Generated by Django 4.2.17 on 2024-12-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_plus_django_app', '0037_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.CharField(default='2024-12-26 | 20:44:05 +0300 | RTZ 2 (зима)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.CharField(default='2024-12-26 | 20:44:05 +0300 | RTZ 2 (зима)'),
        ),
    ]
