# Generated by Django 4.2.17 on 2024-12-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_plus_django_app', '0046_alter_user_created_at_alter_user_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.CharField(default='2024-12-28 | 09:05:19 +0300 | RTZ 2 (зима)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.CharField(default='2024-12-28 | 09:05:19 +0300 | RTZ 2 (зима)'),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
