# Generated by Django 4.2.17 on 2024-12-28 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_plus_django_app', '0047_alter_user_created_at_alter_user_updated_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
