# Generated by Django 4.2.17 on 2024-12-28 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_plus_django_app', '0049_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
